---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=${PASSWORD}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /home/leo/docker/code-server/config:/config
    ports:
      - 8443:8443
    network_mode: host
    restart: unless-stopped
  scsai:
    image: scs-ai:latest
    container_name: scsai-server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /home/leo/docker/scs-ai/config:/config
    ports:
      - 8000:5000
    network_mode: host
    restart: unless-stopped
